### ISSUE TITLE
Issue #6 not solved: log4j settings still overwritten

### ISSUE THREAD

**Issue by igorbga** [Alfresco/alfresco-support-tools#12]
Hi Antonio:

The log4j.properties file's configuration in the module is still overwriting our own configuration. I have a customized alfresco.war that changes the main log4j.properties in order to disable de Console appender and set a fixed absolute path for our log file but when I install the 1.8 version of your module after booting all log ends up in the console appender.

If 1.7.1 did really solve this I guess this might be a regression.

**Comment by igorbga** [comment]
I've been trying by using a custom-log4j.properties files in extensions directory and I see that when I do this I can override your log4j.properties but it does not get loaded until the repository has already bootstrapped, it is loaded a bit later as you already commented somewhere else.

But this has allowed me to see that this way if I don't define de jmxlogger in my custom-log4j the log4j settings screen complains about it being missing, but only in the first refresh then it seems that your code has managed to reactivate it. So if this as I state, shouldn't be better to remove the log4j.properties file in your module and let the jmxlogger reinitialization code take care of bootstrapping it ? This way you won't interfere at all with othe log settings.

**Comment by AntonioSoler** [comment]
Hi,
I meant with resolved that I no longer overwrite the original "log4j.properties" file from the WEB-INF folder so no -F option is needed for deployment.
Of course using multiple "log4.properties" could be tricky because there is no easy way to define the "log4j.rootLogger" variable with several appenders or custom settings.

The important bit is that for that "ad hoc" initialization done from the webscript I only need the JMXlogAppender jar to be in place on the libs folder, doing this you will miss the bootstrap log entries and when used to review the logs it won´t be tailing entries until the webscript is called the very first time.

**Comment by igorbga** [comment]
Ok Antonio,
Thanks for the clarification.
By the way, great job, I really love this module, really useful.
